<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>422636b9-962b-471d-9df6-348a9cd8dcdb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="elk-dotnet-setup\**" />
    <Compile Remove="Prometheus-Grafana-Local\**" />
    <Compile Remove="Prometheus-Grafana\**" />
    <Content Remove="elk-dotnet-setup\**" />
    <Content Remove="Prometheus-Grafana-Local\**" />
    <Content Remove="Prometheus-Grafana\**" />
    <EmbeddedResource Remove="elk-dotnet-setup\**" />
    <EmbeddedResource Remove="Prometheus-Grafana-Local\**" />
    <EmbeddedResource Remove="Prometheus-Grafana\**" />
    <None Remove="elk-dotnet-setup\**" />
    <None Remove="Prometheus-Grafana-Local\**" />
    <None Remove="Prometheus-Grafana\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="CI - CD Setup Guide - .NET 8 Web API with Jenkins and Kubernetes.html" />
    <None Remove="Dockerfile" />
    <None Remove="ingress.yml" />
    <None Remove="integratedapi-deploy.yml" />
    <None Remove="integratedapi-hpa-fixed.yml" />
    <None Remove="Jenkinsfile" />
    <None Remove="Keycloak Authorization flow Guide.html" />
    <None Remove="KeyCloak docker-compose.yml" />
    <None Remove="keycloak-deploy.yml" />
    <None Remove="Kong Config Guide.html" />
    <None Remove="kong-integrated.yml" />
    <None Remove="Kubernetes HPA Setup Guide.html" />
    <None Remove="load-test-hpa-integrated-api.txt" />
    <None Remove="metrics-server-fixed.yaml" />
    <None Remove="Prometheus Grafana Guide.html" />
    <None Remove="sqlserver-deploy.yml" />
    <None Remove="TestLoadBalance.ps1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />

    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />


    <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.0" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.0" />

    <PackageReference Include="Serilog.AspNetCore" Version="4.1.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
    <PackageReference Include="Serilog.Formatting.Elasticsearch" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Http" Version="9.2.1" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.Elasticsearch" Version="8.4.1" />

    <PackageReference Include="Stripe.net" Version="49.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Keycloak.AuthServices.Authorization" Version="2.7.0" />
    <PackageReference Include="Keycloak.AuthServices.Authentication" Version="2.7.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
  </ItemGroup>

</Project>
