---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-postgres-pvc
  labels:
    app: kong-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard  # Change if your cluster uses a different StorageClass

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-database
  labels:
    app: kong-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-database
  template:
    metadata:
      labels:
        app: kong-database
    spec:
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              value: kong
            - name: POSTGRES_DB
              value: kong
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "kong"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "kong"]
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: kong-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: kong-database
  labels:
    app: kong-database
spec:
  type: ClusterIP
  selector:
    app: kong-database
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres

---
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-bootstrap
spec:
  template:
    spec:
      containers:
        - name: kong-migrations
          image: kong:3.4
          env:
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_HOST
              value: kong-database
            - name: KONG_PG_USER
              value: kong
            - name: KONG_PG_PASSWORD
              value: kong
            - name: KONG_PG_DATABASE
              value: kong
          command: ["/bin/sh", "-c", "kong migrations bootstrap && kong migrations up"]
      restartPolicy: OnFailure

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  labels:
    app: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:3.4
          imagePullPolicy: IfNotPresent
          env:
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_HOST
              value: kong-database
            - name: KONG_PG_USER
              value: kong
            - name: KONG_PG_PASSWORD
              value: kong
            - name: KONG_PG_DATABASE
              value: kong
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001, 0.0.0.0:8444 ssl
          ports:
            - name: proxy
              containerPort: 8000
            - name: proxy-ssl
              containerPort: 8443
            - name: admin
              containerPort: 8001
            - name: admin-ssl
              containerPort: 8444
          readinessProbe:
            httpGet:
              path: /status
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  labels:
    app: kong
spec:
  type: NodePort     # Use LoadBalancer if on a managed cloud cluster
  ports:
    - name: kong-admin
      port: 8001
      targetPort: 8001
      nodePort: 30001
  selector:
    app: kong

---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  labels:
    app: kong
spec:
  type: NodePort     # Use LoadBalancer if you want external access to APIs
  ports:
    - name: kong-proxy
      port: 8000
      targetPort: 8000
      nodePort: 30000
    - name: kong-proxy-ssl
      port: 8443
      targetPort: 8443
      nodePort: 30443
  selector:
    app: kong
