apiVersion: apps/v1
kind: Deployment
metadata:
  name: integratedapi-deployment
  labels:
    app: integratedapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integratedapi
  template:
    metadata:
      labels:
        app: integratedapi
    spec:
      containers:
        - name: integratedapi
          image: karthiknat/integratedapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: integratedapi-service
  labels:
    app: integratedapi
spec:
  type: ClusterIP
  selector:
    app: integratedapi
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
