services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault-enterprise
    ports:
      - "8200:8200"
    volumes:
      - ./config:/vault/config
      - ./data:/vault/data
      - ./logs:/vault/logs
      - ./tls:/vault/tls:ro
    cap_add:
      - IPC_LOCK
    entrypoint: sh
    command: -c "vault server -config=/vault/config/vault.hcl"